spring:
  profile:
    active:
    - dev
---
spring:
  profile: dev
  application:
    name: microservicecloud-config-bytedance-dev
---
spring:
  profile: test
  application:
    name: microservicecloud-config-bytedance-test